# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64b0c5a3f4d77b023a838c0809b015aa06b9201e6615b6d06e35168ad10948b7ae096748bfa0a387af7493a011085005a5c9ab1c7fe96ba0346e9d2f66d5bdb9

test:
  secret_key_base: b78248862c3a085a1cb07c6bbb0a87921a4e70e232a72955d47164936dee67a4e7dc37a75c1d8a2a48409c5cf334b0067001cfc7d7b2919cb1ef471f34b39fd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
